import {
  Atom,
  Backpack,
  Book,
  BookOpen,
  Briefcase,
  Calculator,
  Dumbbell,
  FlaskConical,
  Footprints,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Headphones,
  Heart,
  Landmark,
  Laptop,
  Layers,
  Library,
  NotebookPen,
  Package,
  Palette,
  PenLine,
  Pencil,
  Ruler,
  School,
  Shirt,
  ShoppingBag,
  Star,
  Tag,
  Trophy,
  Watch,
} from 'lucide-react';

export const CATEGORY_ICONS = [
  { key: 'layers', label: 'General', Icon: Layers },
  { key: 'book-open', label: 'Books', Icon: BookOpen },
  { key: 'book', label: 'Book', Icon: Book },
  { key: 'library', label: 'Library', Icon: Library },
  { key: 'graduation-cap', label: 'Education', Icon: GraduationCap },
  { key: 'school', label: 'School', Icon: School },
  { key: 'backpack', label: 'Bags', Icon: Backpack },
  { key: 'shopping-bag', label: 'Shopping', Icon: ShoppingBag },
  { key: 'briefcase', label: 'Office', Icon: Briefcase },
  { key: 'shirt', label: 'Uniforms', Icon: Shirt },
  { key: 'footprints', label: 'Shoes', Icon: Footprints },
  { key: 'dumbbell', label: 'Sports', Icon: Dumbbell },
  { key: 'trophy', label: 'Trophy', Icon: Trophy },
  { key: 'pencil', label: 'Stationery', Icon: Pencil },
  { key: 'pen-line', label: 'Writing', Icon: PenLine },
  { key: 'notebook-pen', label: 'Notebook', Icon: NotebookPen },
  { key: 'ruler', label: 'Tools', Icon: Ruler },
  { key: 'palette', label: 'Art', Icon: Palette },
  { key: 'laptop', label: 'Tech', Icon: Laptop },
  { key: 'headphones', label: 'Audio', Icon: Headphones },
  { key: 'glasses', label: 'Glasses', Icon: Glasses },
  { key: 'watch', label: 'Accessories', Icon: Watch },
  { key: 'gift', label: 'Gifts', Icon: Gift },
  { key: 'heart', label: 'Favorites', Icon: Heart },
  { key: 'star', label: 'Featured', Icon: Star },
  { key: 'tag', label: 'Sale', Icon: Tag },
  { key: 'package', label: 'Packs', Icon: Package },
  { key: 'landmark', label: 'Campus', Icon: Landmark },
  { key: 'atom', label: 'Science', Icon: Atom },
  { key: 'flask-conical', label: 'Lab', Icon: FlaskConical },
  { key: 'calculator', label: 'Math', Icon: Calculator },
  { key: 'globe', label: 'World', Icon: Globe },
];

const ICON_MAP = Object.fromEntries(CATEGORY_ICONS.map((i) => [i.key, i.Icon]));

export function getCategoryIcon(key) {
  return ICON_MAP[key] || Layers;
}
