/** In-memory demo dataset for Dashboard without Backend */

export const DEMO_ADMIN = {
  id: 'demo-admin-1',
  name: 'Ali Merchant',
  email: 'admin@demo-books.local',
  phone: '03001234567',
  role: 'administrator',
  storeId: 'demo-store-1',
  isVerified: true,
  isActive: true,
};

export const DEMO_CREDENTIALS = {
  email: 'admin@demo-books.local',
  password: 'Admin@12345',
};

const now = Date.now();
const day = 24 * 60 * 60 * 1000;

export const demoDb = {
  store: {
    _id: 'demo-store-1',
    name: 'BookVerse',
    slug: 'bookverse',
    customDomain: 'bookverse.pk',
    logoUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e1d843b?w=200&q=80',
    bannerUrls: [
      'https://images.unsplash.com/photo-1507842217343-583bb7270b66?w=1400&q=80',
      'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=1400&q=80',
      'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=1400&q=80',
    ],
    faviconUrl: 'https://images.unsplash.com/photo-1481627834876-b7833e1d843b?w=64&q=80',
    themeColors: { primary: '#1e1b4b', secondary: '#5b21b6', accent: '#7c3aed' },
    contactEmail: 'hello@bookverse.pk',
    contactPhone: '03001234567',
    address: '12 Book Lane, Gulberg III, Lahore 54000',
    socialLinks: {
      facebook: 'https://facebook.com/bookverse',
      instagram: 'https://instagram.com/bookverse',
      twitter: 'https://twitter.com/bookverse',
    },
    websiteContent: {
      aboutTitle: 'About BookVerse',
      aboutBody:
        'BookVerse is a modern Pakistani bookstore bringing carefully curated titles, stationery, and everyday carry essentials to readers nationwide. From bestsellers to campus essentials, we ship with care and pride.',
      aboutMission:
        'To make great reading accessible — with honest prices, fast COD, and a storefront that feels like a neighborhood bookshop.',
      aboutVision:
        'A BookVerse shelf in every Pakistani home, and a digital storefront that rivals the warmth of walking into a real bookstore.',
      contactTitle: 'Get in touch',
      contactBody:
        'Questions about an order, a rare title, or wholesale? Email or WhatsApp us — we typically reply within a few hours during business days.',
      homepageHeadline: 'Find your next favorite read',
      homepageSubheadline: 'Curated books, stationery & more — delivered across Pakistan.',
      footerText: '© BookVerse. Crafted for readers across Pakistan.',
      termsBody:
        'By placing an order on BookVerse you agree that product availability, pricing, and delivery estimates may change. COD orders may be verified by phone. Returns for damaged items must be reported within 48 hours of delivery with photo evidence. BookVerse reserves the right to cancel fraudulent or incomplete orders.',
      privacyBody:
        'We collect name, phone, email, and shipping details solely to fulfill orders and improve your experience. Payment data for JazzCash/Easypaisa is processed by those providers. We never sell personal data. Contact hello@bookverse.pk to request data deletion.',
      faqBody:
        'Q: Do you offer COD?\nA: Yes, nationwide with optional phone verification.\n\nQ: How long is delivery?\nA: Major cities 2–4 days; other areas 4–7 days.\n\nQ: Can I return a book?\nA: Sealed books are final sale unless damaged in transit.\n\nQ: Do you gift wrap?\nA: Yes — add a note at checkout and we will include complimentary gift wrap when stock allows.',
      shippingBody:
        'We ship via trusted couriers across Pakistan. Free shipping on orders over PKR 2,500. Standard fee PKR 200 below that threshold. Tracking links are emailed/SMS’d once your parcel is handed to the courier. Remote areas may take longer; we will notify you if a delay is expected.',
    },
    subscriptionStatus: 'trial',
    isActive: true,
    isLive: true,
  },
  categories: [
    { _id: 'cat-1', name: 'Books', slug: 'books', isActive: true, sortOrder: 1 },
    { _id: 'cat-2', name: 'Stationery', slug: 'stationery', isActive: true, sortOrder: 2 },
    { _id: 'cat-3', name: 'Bags', slug: 'bags', isActive: true, sortOrder: 3 },
  ],
  products: [
    {
      _id: 'prod-1',
      title: 'The Silent Patient',
      slug: 'the-silent-patient',
      sku: 'BK-001',
      categoryId: 'cat-1',
      price: 1200,
      discountPrice: 999,
      stockQuantity: 42,
      lowStockThreshold: 5,
      soldCount: 1240,
      isPublished: true,
      description: 'A gripping psychological thriller about a woman’s act of violence against her husband—and the therapist obsessed with uncovering her motive.',
      images: ['https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400&q=80'],
      specifications: [
        { key: 'Author', value: 'Alex Michaelides' },
        { key: 'Pages', value: '336' },
        { key: 'Language', value: 'English' },
      ],
    },
    {
      _id: 'prod-2',
      title: 'Atomic Habits',
      slug: 'atomic-habits',
      sku: 'BK-002',
      categoryId: 'cat-1',
      price: 1500,
      discountPrice: null,
      stockQuantity: 3,
      lowStockThreshold: 5,
      soldCount: 980,
      isPublished: true,
      description: 'Tiny changes, remarkable results — a practical framework for building good habits and breaking bad ones.',
      images: ['https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400&q=80'],
      specifications: [
        { key: 'Author', value: 'James Clear' },
        { key: 'Pages', value: '320' },
      ],
    },
    {
      _id: 'prod-3',
      title: 'Campus Backpack',
      slug: 'campus-backpack',
      sku: 'BG-001',
      categoryId: 'cat-3',
      price: 3500,
      discountPrice: 2999,
      stockQuantity: 18,
      lowStockThreshold: 5,
      soldCount: 420,
      isPublished: true,
      description: 'Water-resistant backpack with padded laptop sleeve and multiple organizer pockets.',
      images: ['https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&q=80'],
      specifications: [
        { key: 'Capacity', value: '25L' },
        { key: 'Material', value: 'Nylon' },
      ],
    },
    {
      _id: 'prod-4',
      title: 'Notebook Set',
      slug: 'notebook-set',
      sku: 'ST-001',
      categoryId: 'cat-2',
      price: 650,
      discountPrice: null,
      stockQuantity: 0,
      lowStockThreshold: 10,
      soldCount: 210,
      isPublished: false,
      description: 'Set of 3 hardcover ruled notebooks — ideal for class notes or journaling.',
      images: ['https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=400&q=80'],
      specifications: [{ key: 'Pack', value: '3 notebooks' }],
    },
    {
      _id: 'prod-5',
      title: 'Ikigai',
      slug: 'ikigai',
      sku: 'BK-003',
      categoryId: 'cat-1',
      price: 1100,
      discountPrice: 890,
      stockQuantity: 27,
      lowStockThreshold: 5,
      soldCount: 640,
      isPublished: true,
      description: 'The Japanese secret to a long and happy life — purpose, community, and daily joy.',
      images: ['https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400&q=80'],
      specifications: [
        { key: 'Author', value: 'Héctor García' },
        { key: 'Pages', value: '208' },
      ],
    },
    {
      _id: 'prod-6',
      title: 'Fountain Pen Set',
      slug: 'fountain-pen-set',
      sku: 'ST-002',
      categoryId: 'cat-2',
      price: 2200,
      discountPrice: 1899,
      stockQuantity: 12,
      lowStockThreshold: 4,
      soldCount: 155,
      isPublished: true,
      description: 'Elegant metal fountain pen with converter and two ink cartridges.',
      images: ['https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=400&q=80'],
      specifications: [
        { key: 'Nib', value: 'Medium' },
        { key: 'Includes', value: 'Converter + 2 cartridges' },
      ],
    },
    {
      _id: 'prod-7',
      title: 'Sapiens',
      slug: 'sapiens',
      sku: 'BK-004',
      categoryId: 'cat-1',
      price: 1800,
      discountPrice: 1499,
      stockQuantity: 4,
      lowStockThreshold: 5,
      soldCount: 870,
      isPublished: true,
      description: 'A brief history of humankind — from foraging bands to global empires.',
      images: ['https://images.unsplash.com/photo-1589998059171-988d887df646?w=400&q=80'],
      specifications: [
        { key: 'Author', value: 'Yuval Noah Harari' },
        { key: 'Pages', value: '512' },
      ],
    },
    {
      _id: 'prod-8',
      title: 'Leather Tote Bag',
      slug: 'leather-tote-bag',
      sku: 'BG-002',
      categoryId: 'cat-3',
      price: 4800,
      discountPrice: null,
      stockQuantity: 9,
      lowStockThreshold: 3,
      soldCount: 96,
      isPublished: true,
      description: 'Handsome vegan-leather tote with magnetic closure — perfect for market days and campus runs.',
      images: ['https://images.unsplash.com/photo-1590874103328-eac38a67478e?w=400&q=80'],
      specifications: [
        { key: 'Material', value: 'Vegan leather' },
        { key: 'Color', value: 'Cognac' },
      ],
    },
  ],
  orders: [
    {
      _id: 'ord-1',
      orderNumber: 'ORD-20260803-0001',
      customerId: { name: 'Sara Ahmed', email: 'sara@example.com', phone: '03011112222' },
      items: [
        {
          productId: 'prod-1',
          title: 'The Silent Patient',
          sku: 'BK-001',
          imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=200&q=80',
          unitPrice: 999,
          quantity: 1,
          subtotal: 999,
        },
      ],
      shippingAddress: {
        name: 'Sara Ahmed',
        phone: '03011112222',
        email: 'sara@example.com',
        addressLine: '12 Gulberg',
        city: 'Lahore',
        postalCode: '54000',
      },
      subtotal: 999,
      discountAmount: 0,
      shippingFee: 200,
      taxAmount: 0,
      totalAmount: 1199,
      paymentMethod: 'cod',
      paymentStatus: 'pending',
      orderStatus: 'pending',
      customerNote: 'Please call before delivery.',
      statusHistory: [{ status: 'pending', changedAt: new Date(now - 2 * day).toISOString(), note: 'Order placed' }],
      createdAt: new Date(now - 2 * day).toISOString(),
    },
    {
      _id: 'ord-2',
      orderNumber: 'ORD-20260802-0004',
      customerId: { name: 'Hassan Raza', email: 'hassan@example.com', phone: '03023334444' },
      items: [
        {
          productId: 'prod-2',
          title: 'Atomic Habits',
          sku: 'BK-002',
          imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=200&q=80',
          unitPrice: 1500,
          quantity: 2,
          subtotal: 3000,
        },
      ],
      shippingAddress: {
        name: 'Hassan Raza',
        phone: '03023334444',
        email: 'hassan@example.com',
        addressLine: '45 DHA Phase 5',
        city: 'Karachi',
        postalCode: '75500',
      },
      subtotal: 3000,
      discountAmount: 300,
      shippingFee: 0,
      taxAmount: 0,
      totalAmount: 2700,
      paymentMethod: 'jazzcash',
      paymentStatus: 'paid',
      orderStatus: 'processing',
      statusHistory: [
        { status: 'pending', changedAt: new Date(now - 5 * day).toISOString(), note: 'Order placed' },
        { status: 'processing', changedAt: new Date(now - 4 * day).toISOString(), note: 'Payment confirmed' },
      ],
      createdAt: new Date(now - 5 * day).toISOString(),
    },
    {
      _id: 'ord-3',
      orderNumber: 'ORD-20260728-0012',
      customerId: { name: 'Ayesha Khan', email: 'ayesha@example.com', phone: '03035556666' },
      items: [
        {
          productId: 'prod-3',
          title: 'Campus Backpack',
          sku: 'BG-001',
          imageUrl: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=200&q=80',
          unitPrice: 2999,
          quantity: 1,
          subtotal: 2999,
        },
      ],
      shippingAddress: {
        name: 'Ayesha Khan',
        phone: '03035556666',
        email: 'ayesha@example.com',
        addressLine: '7 F-7 Markaz',
        city: 'Islamabad',
        postalCode: '44000',
      },
      subtotal: 2999,
      discountAmount: 0,
      shippingFee: 0,
      taxAmount: 0,
      totalAmount: 2999,
      paymentMethod: 'easypaisa',
      paymentStatus: 'paid',
      orderStatus: 'delivered',
      statusHistory: [
        { status: 'pending', changedAt: new Date(now - 10 * day).toISOString() },
        { status: 'processing', changedAt: new Date(now - 9 * day).toISOString() },
        { status: 'shipped', changedAt: new Date(now - 8 * day).toISOString() },
        { status: 'delivered', changedAt: new Date(now - 6 * day).toISOString(), note: 'Delivered to customer' },
      ],
      createdAt: new Date(now - 10 * day).toISOString(),
    },
    {
      _id: 'ord-4',
      orderNumber: 'ORD-20260801-0008',
      customerId: { name: 'Bilal Hussain', email: 'bilal@example.com', phone: '03047778888' },
      items: [
        {
          productId: 'prod-5',
          title: 'Ikigai',
          sku: 'BK-003',
          imageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=200&q=80',
          unitPrice: 890,
          quantity: 1,
          subtotal: 890,
        },
        {
          productId: 'prod-6',
          title: 'Fountain Pen Set',
          sku: 'ST-002',
          imageUrl: 'https://images.unsplash.com/photo-1585336261022-680e295ce3fe?w=200&q=80',
          unitPrice: 1899,
          quantity: 1,
          subtotal: 1899,
        },
      ],
      shippingAddress: {
        name: 'Bilal Hussain',
        phone: '03047778888',
        email: 'bilal@example.com',
        addressLine: '88 Model Town',
        city: 'Lahore',
        postalCode: '54700',
      },
      subtotal: 2789,
      discountAmount: 200,
      shippingFee: 0,
      taxAmount: 0,
      totalAmount: 2589,
      paymentMethod: 'jazzcash',
      paymentStatus: 'paid',
      orderStatus: 'shipped',
      statusHistory: [
        { status: 'pending', changedAt: new Date(now - 7 * day).toISOString() },
        { status: 'processing', changedAt: new Date(now - 6 * day).toISOString() },
        { status: 'shipped', changedAt: new Date(now - 3 * day).toISOString(), note: 'Handed to courier' },
      ],
      createdAt: new Date(now - 7 * day).toISOString(),
    },
    {
      _id: 'ord-5',
      orderNumber: 'ORD-20260725-0020',
      customerId: { name: 'Fatima Noor', email: 'fatima@example.com', phone: '03059990000' },
      items: [
        {
          productId: 'prod-7',
          title: 'Sapiens',
          sku: 'BK-004',
          imageUrl: 'https://images.unsplash.com/photo-1589998059171-988d887df646?w=200&q=80',
          unitPrice: 1499,
          quantity: 1,
          subtotal: 1499,
        },
      ],
      shippingAddress: {
        name: 'Fatima Noor',
        phone: '03059990000',
        email: 'fatima@example.com',
        addressLine: '3 Clifton Block 5',
        city: 'Karachi',
        postalCode: '75600',
      },
      subtotal: 1499,
      discountAmount: 0,
      shippingFee: 200,
      taxAmount: 0,
      totalAmount: 1699,
      paymentMethod: 'cod',
      paymentStatus: 'paid',
      orderStatus: 'delivered',
      statusHistory: [
        { status: 'pending', changedAt: new Date(now - 14 * day).toISOString() },
        { status: 'processing', changedAt: new Date(now - 13 * day).toISOString() },
        { status: 'shipped', changedAt: new Date(now - 12 * day).toISOString() },
        { status: 'delivered', changedAt: new Date(now - 11 * day).toISOString() },
      ],
      createdAt: new Date(now - 14 * day).toISOString(),
    },
    {
      _id: 'ord-6',
      orderNumber: 'ORD-20260720-0031',
      customerId: { name: 'Omar Sheikh', email: 'omar@example.com', phone: '03121112233' },
      items: [
        {
          productId: 'prod-8',
          title: 'Leather Tote Bag',
          sku: 'BG-002',
          imageUrl: 'https://images.unsplash.com/photo-1590874103328-eac38a67478e?w=200&q=80',
          unitPrice: 4800,
          quantity: 1,
          subtotal: 4800,
        },
      ],
      shippingAddress: {
        name: 'Omar Sheikh',
        phone: '03121112233',
        email: 'omar@example.com',
        addressLine: '21 University Road',
        city: 'Peshawar',
        postalCode: '25000',
      },
      subtotal: 4800,
      discountAmount: 0,
      shippingFee: 250,
      taxAmount: 0,
      totalAmount: 5050,
      paymentMethod: 'easypaisa',
      paymentStatus: 'refunded',
      orderStatus: 'cancelled',
      refund: {
        amount: 5050,
        reason: 'Customer changed mind before dispatch',
        refundedAt: new Date(now - 16 * day).toISOString(),
      },
      statusHistory: [
        { status: 'pending', changedAt: new Date(now - 18 * day).toISOString() },
        { status: 'processing', changedAt: new Date(now - 17 * day).toISOString() },
        { status: 'cancelled', changedAt: new Date(now - 16 * day).toISOString(), note: 'Refund issued' },
      ],
      createdAt: new Date(now - 18 * day).toISOString(),
    },
    {
      _id: 'ord-7',
      orderNumber: 'ORD-20260804-0002',
      customerId: { name: 'Zainab Ali', email: 'zainab@example.com', phone: '03223334455' },
      items: [
        {
          productId: 'prod-1',
          title: 'The Silent Patient',
          sku: 'BK-001',
          imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=200&q=80',
          unitPrice: 999,
          quantity: 1,
          subtotal: 999,
        },
        {
          productId: 'prod-5',
          title: 'Ikigai',
          sku: 'BK-003',
          imageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=200&q=80',
          unitPrice: 890,
          quantity: 2,
          subtotal: 1780,
        },
      ],
      shippingAddress: {
        name: 'Zainab Ali',
        phone: '03223334455',
        email: 'zainab@example.com',
        addressLine: '55 Bahria Town',
        city: 'Rawalpindi',
        postalCode: '46000',
      },
      subtotal: 2779,
      discountAmount: 277,
      shippingFee: 0,
      taxAmount: 0,
      totalAmount: 2502,
      paymentMethod: 'jazzcash',
      paymentStatus: 'paid',
      orderStatus: 'out_for_delivery',
      statusHistory: [
        { status: 'pending', changedAt: new Date(now - 1 * day).toISOString() },
        { status: 'processing', changedAt: new Date(now - 0.8 * day).toISOString() },
        { status: 'shipped', changedAt: new Date(now - 0.4 * day).toISOString() },
        { status: 'out_for_delivery', changedAt: new Date(now - 0.1 * day).toISOString(), note: 'Out with rider' },
      ],
      createdAt: new Date(now - 1 * day).toISOString(),
    },
    {
      _id: 'ord-8',
      orderNumber: 'ORD-20260715-0044',
      customerId: { name: 'Usman Tariq', email: 'usman@example.com', phone: '03334445566' },
      items: [
        {
          productId: 'prod-4',
          title: 'Notebook Set',
          sku: 'ST-001',
          imageUrl: 'https://images.unsplash.com/photo-1531346878377-a5be20888e57?w=200&q=80',
          unitPrice: 650,
          quantity: 3,
          subtotal: 1950,
        },
      ],
      shippingAddress: {
        name: 'Usman Tariq',
        phone: '03334445566',
        email: 'usman@example.com',
        addressLine: '9 Satellite Town',
        city: 'Gujranwala',
        postalCode: '52250',
      },
      subtotal: 1950,
      discountAmount: 0,
      shippingFee: 200,
      taxAmount: 0,
      totalAmount: 2150,
      paymentMethod: 'cod',
      paymentStatus: 'pending',
      orderStatus: 'processing',
      statusHistory: [
        { status: 'pending', changedAt: new Date(now - 22 * day).toISOString() },
        { status: 'processing', changedAt: new Date(now - 21 * day).toISOString() },
      ],
      createdAt: new Date(now - 22 * day).toISOString(),
    },
  ],
  discounts: [
    {
      _id: 'disc-1',
      code: 'WELCOME10',
      type: 'percentage',
      value: 10,
      minOrderAmount: 500,
      startDate: new Date(now - 30 * day).toISOString(),
      endDate: new Date(now + 60 * day).toISOString(),
      usageLimit: 1000,
      usedCount: 24,
      isActive: true,
    },
    {
      _id: 'disc-2',
      code: 'FLAT200',
      type: 'fixed',
      value: 200,
      minOrderAmount: 2000,
      startDate: new Date(now - 7 * day).toISOString(),
      endDate: new Date(now + 14 * day).toISOString(),
      usageLimit: 100,
      usedCount: 8,
      isActive: true,
    },
    {
      _id: 'disc-3',
      code: 'READMORE15',
      type: 'percentage',
      value: 15,
      minOrderAmount: 1500,
      startDate: new Date(now - 14 * day).toISOString(),
      endDate: new Date(now + 45 * day).toISOString(),
      usageLimit: 500,
      usedCount: 41,
      isActive: true,
    },
    {
      _id: 'disc-4',
      code: 'BAGS500',
      type: 'fixed',
      value: 500,
      minOrderAmount: 3500,
      startDate: new Date(now - 3 * day).toISOString(),
      endDate: new Date(now + 30 * day).toISOString(),
      usageLimit: 50,
      usedCount: 3,
      isActive: true,
    },
    {
      _id: 'disc-5',
      code: 'SUMMER25',
      type: 'percentage',
      value: 25,
      minOrderAmount: 3000,
      startDate: new Date(now - 60 * day).toISOString(),
      endDate: new Date(now - 5 * day).toISOString(),
      usageLimit: 200,
      usedCount: 200,
      isActive: false,
    },
  ],
  reviews: [
    {
      _id: 'rev-1',
      productId: 'prod-1',
      product: 'The Silent Patient',
      customer: 'Sara Ahmed',
      rating: 5,
      comment: 'Loved the twist ending. Fast delivery too!',
      status: 'pending',
      createdAt: new Date(now - 4 * day).toISOString(),
    },
    {
      _id: 'rev-2',
      productId: 'prod-2',
      product: 'Atomic Habits',
      customer: 'Hassan Raza',
      rating: 4,
      comment: 'Practical and easy to apply. Packaging was good.',
      status: 'approved',
      createdAt: new Date(now - 12 * day).toISOString(),
    },
    {
      _id: 'rev-3',
      productId: 'prod-3',
      product: 'Campus Backpack',
      customer: 'Ayesha Khan',
      rating: 3,
      comment: 'Decent quality for the price. Straps could be softer.',
      status: 'rejected',
      createdAt: new Date(now - 20 * day).toISOString(),
    },
    {
      _id: 'rev-4',
      productId: 'prod-5',
      product: 'Ikigai',
      customer: 'Bilal Hussain',
      rating: 5,
      comment: 'A calming read. Gift-wrapped beautifully.',
      status: 'approved',
      createdAt: new Date(now - 6 * day).toISOString(),
    },
    {
      _id: 'rev-5',
      productId: 'prod-7',
      product: 'Sapiens',
      customer: 'Fatima Noor',
      rating: 5,
      comment: 'Mind-expanding. Arrived a day early!',
      status: 'pending',
      createdAt: new Date(now - 3 * day).toISOString(),
    },
    {
      _id: 'rev-6',
      productId: 'prod-6',
      product: 'Fountain Pen Set',
      customer: 'Zainab Ali',
      rating: 4,
      comment: 'Smooth write. Looks premium on the desk.',
      status: 'approved',
      createdAt: new Date(now - 8 * day).toISOString(),
    },
  ],
  refunds: [],
};

/** Build transaction list from orders (and refunds) for billing views */
export function buildTransactionsFromOrders(orders = demoDb.orders) {
  return orders.map((o) => ({
    _id: `txn-${o._id}`,
    transactionId: `TXN-${String(o.orderNumber || o._id).replace(/^ORD-/, '')}`,
    orderId: o._id,
    orderNumber: o.orderNumber,
    date: o.createdAt,
    amount: o.paymentStatus === 'refunded' ? -(o.refund?.amount ?? o.totalAmount) : o.totalAmount,
    paymentMethod: o.paymentMethod,
    paymentType: o.paymentMethod,
    status: o.paymentStatus,
    customer: o.shippingAddress?.name || o.customerId?.name || '—',
    order: o,
  }));
}

export function getDemoSession() {
  try {
    const raw = sessionStorage.getItem('bookstore_demo_session');
    return raw ? JSON.parse(raw) : null;
  } catch {
    return null;
  }
}

export function setDemoSession(user) {
  sessionStorage.setItem('bookstore_demo_session', JSON.stringify(user));
}

export function clearDemoSession() {
  sessionStorage.removeItem('bookstore_demo_session');
}

export function ok(data, message = 'Success', meta = null) {
  const body = { success: true, message, data };
  if (meta) body.meta = meta;
  return body;
}

export function fail(message, status = 400) {
  const error = new Error(message);
  error.response = { status, data: { success: false, message } };
  throw error;
}
